services:
  web:
    image: nginx:latest
    container_name: nginxexternal
    # volumes:
    #   - /home/ubuntu/docker/nginx/templates:/etc/nginx/templates
    #   - /home/ubuntu/docker/nginx/web:/usr/share/nginx/html
    environment:
      - NGINX_HOST=nginx.limesour.my.id
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=http-external"
      - "traefik.http.routers.nginx.rule=Host(`nginx.limesour.my.id`)"
      - "traefik.http.middlewares.nginx-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nginx.middlewares=nginx-https-redirect"
      - "traefik.http.routers.nginx-secure.entrypoints=https-external"
      - "traefik.http.routers.nginx-secure.rule=Host(`nginx.limesour.my.id`)"
      - "traefik.http.routers.nginx-secure.middlewares=default-headers@file"
      - "traefik.http.routers.nginx-secure.tls=true"
      - "traefik.http.routers.nginx-secure.service=nginx"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      proxy:
    security_opt:
      - no-new-privileges:true
  
networks:
  proxy:
    external: true